### ISSUE TITLE
Pyvistaqt incompatible with pyvista==0.30.0

### ISSUE THREAD

**Issue by jorgensd** [pyvista/pyvistaqt#105]
The following MWE works using `pyvista==0.29.1`:
```
import pyvista as pv
import pyvistaqt as pvqt
if pv.OFF_SCREEN:
    pv.start_xvfb(wait=0)
p = pvqt.BackgroundPlotter(title="concentration", auto_update=True)
```
but crashes using `pyvista==0.30.0` with the following: 
- `PYVISTA_OFF_SCREEN=False`: 
```
Traceback (most recent call last):
  File "qt_fail.py", line 5, in <module>
    p = pvqt.BackgroundPlotter(title="concentration", auto_update=True)
  File "/usr/local/lib/python3.8/dist-packages/pyvistaqt/plotting.py", line 631, in __init__
    super(BackgroundPlotter, self).__init__(
  File "/usr/local/lib/python3.8/dist-packages/pyvistaqt/plotting.py", line 259, in __init__
    self._add_observer("KeyPressEvent", self.key_press_event)
  File "/usr/local/lib/python3.8/dist-packages/vtkmodules/qt/QVTKRenderWindowInteractor.py", line 335, in __getattr__
    raise AttributeError(self.__class__.__name__ +
AttributeError: BackgroundPlotter has no attribute named _add_observer
```
- `PYVISTA_OFF_SCREEN=True`
```
  File "qt_fail.py", line 5, in <module>
    p = pvqt.BackgroundPlotter(title="concentration", auto_update=True)
  File "/usr/local/lib/python3.8/dist-packages/pyvistaqt/plotting.py", line 682, in __init__
    self.add_key_event("S", self._qt_screenshot)  # shift + s
  File "/usr/local/lib/python3.8/dist-packages/pyvista/plotting/plotting.py", line 785, in add_key_event
    self.iren.add_key_event(*args, **kwargs)
AttributeError: 'NoneType' object has no attribute 'add_key_event'
```

**Comment by GuillaumeFavelier** [comment]
Hello @jorgensd and thank you for reporting this, do you mean `pyvista 0.30.0`? I saw it coming :) 

This should be fixed in the recent PRs, mainly #97 and #95. We should release `0.4.0` soon to make it more convenient for everybody but in my opinion not until https://github.com/pyvista/pyvistaqt/pull/100 is merged. 

So, a short-term solution for you would be to install the latest `master`(8eb4040) version. Do not hesitate to tell me if that is helpful.

**Comment by GuillaumeFavelier** [comment]
@jorgensd, `pyvistaqt 0.4.0` is now released :+1:

**Comment by jorgensd** [comment]
Tested locally, and pyvistaqt now works again!:) Thanks!
